SELECT LL.*, LEFT(TT.celula,CHARINDEX(' ',TT.celula)-1) AS celula
INTO #LISTA1
FROM #LISTA AS LL
LEFT JOIN NETWIN_TOTAIS..ENDERECOS_TOTAIS AS TT
ON LL.COD_SURVEY = TT.cod_survey



SELECT UF,ANG,NOME_CDO,COD_SURVEY
INTO #LISTA
FROM ASSOCIADOS..surveys_cdo AS SS

SELECT * FROM #LISTA1


SELECT LL.celula, LL.ANG,LL.UF, LL.NOME_CDO, LL.COD_SURVEY, AA.[CDOE I],AA.[Código Survey],AA.[CFS ACESSOGPON]
INTO #LISTA_PARCIAL
FROM #LISTA1 AS LL
INNER JOIN ASSOCIADOS..SERV_ASSOCIADOS AS AA
ON LL.UF = AA.[Sigla Unidade Federativa] AND LL.ANG = AA.[Sigla Est Abastecedora] AND LL.celula = AA.[Célula CEOS] AND LL.NOME_CDO = AA.[CDOE I]

DROP TABLE #ASSOCIADOS_TOTAIS

SELECT LL.*, TT.nome_cdo AS CDO_TOTAIS,TT.cod_survey AS SURVEY_TOTAIS, TT.cod_viabilidade, TT.qtd_ums
INTO #ASSOCIADOS_TOTAIS
FROM NETWIN_TOTAIS..ENDERECOS_TOTAIS AS TT
RIGHT JOIN #LISTA_PARCIAL AS LL
ON TT.cod_survey = LL.[Código Survey]


SELECT CDO_TOTAIS, SUM(CAST(qtd_ums AS INT)) AS QTD_UMS
FROM #ASSOCIADOS_TOTAIS
GROUP BY [CDO_TOTAIS]

SELECT * FROM #ASSOCIADOS_TOTAIS

--SELECT TT.nome_cdo, SUM(TT.qtd_ums)
--FROM #ASSOCIADOS_TOTAIS AS AA
--LEFT JOIN NETWIN_TOTAIS..ENDERECOS_TOTAIS AS TT
--ON AA.[CDOE I] = TT.nome_cdo
--GROUP BY AA.[CDOE I]

select [Código Survey], [CFS ACESSOGPON]
from ASSOCIADOS..SERV_ASSOCIADOS
where [Código Survey]
= 'R1157496'



SELECT nome_cdo ,cod_viabilidade , qtd_ums, cod_survey
FROM NETWIN_TOTAIS..ENDERECOS_TOTAIS
WHERE cod_survey = --'R1577121','V79488')
'R1168817'


SELECT  AA.celula, AA.ANG, AA.UF, AA.NOME_CDO, AA.COD_SURVEY, TT.cod_survey, TT.nome_cdo, TT.cod_viabilidade, TT.qtd_ums
FROM #ASSOCIADOS_TOTAIS AS AA
LEFT JOIN NETWIN_TOTAIS..ENDERECOS_TOTAIS AS TT
ON AA.COD_SURVEY = TT.cod_survey