DROP TABLE IF EXISTS END_TOTAIS.dbo.Netwin_Totais
SELECT *
INTO END_TOTAIS.dbo.Netwin_Totais
FROM OPENROWSET(  
BULK 'C:\LOGICTEL\DOWNLOAD\Enderecos_Totais_20231127.csv',  
FORMATFILE = 'C:\LOGICTEL\DOWNLOAD\BIEL\totais.xml',
FIRSTROW = 2,
CODEPAGE = 1252) AS TT


DROP TABLE IF EXISTS LISTAGEM.dbo.LISTAGEM_SURVEY
SELECT *
--INTO LISTAGEM.dbo.LISTAGEM_SURVEY
FROM OPENROWSET(  
BULK 'C:\LOGICTEL\DOWNLOAD\LISTAGEM_DE_SURVEYS_2023-10-16_00h04m.csv',  
FORMATFILE = 'C:\LOGICTEL\10-XML\geral.xml',
FIRSTROW = 2,
CODEPAGE = 1252)  AS LL