--/****** Script do comando SelectTopNRows de SSMS  ******/
--SELECT  *
--  FROM [END_TOTAIS].[dbo].[listacells]
--  LEFT JOIN OPENROWSET(  
--	BULK 'C:\LOGICTEL\DOWNLOAD\Enderecos_Totais_20230417.csv',  
--	FORMATFILE = 'C:\LOGICTEL\DOWNLOAD\BIEL\totais.xml',
--	FIRSTROW = 2) AS TT
--	ON [listacells].UF = [TT].uf AND
--	--[listacells].ANG = [TT].estacao_abastecedora AND
--	--[TT].celula LIKE [listacells].CELULA + ' (' + listacells.ANG + '%'




 --SELECT * 
 --FROM OPENROWSET(  
	--	BULK 'C:\LOGICTEL\DOWNLOAD\Enderecos_Totais_20230417.csv',  
	--	FORMATFILE = 'C:\LOGICTEL\DOWNLOAD\BIEL\totais.xml',
	--	FIRSTROW = 2) AS TT
	--	WHERE uf = 'RJ' AND estacao_abastecedora = 'FRE' AND celula LIKE '%154%'

/*
					ANALISA SN
*/

	SELECT trim(T1.CHAVE) AS CHAVE ,T1.SN
	FROM GERA_TABELA_DO_TOTAIS_COM_SN AS T1
	WHERE T1.CHAVE = 'RJJAC3'-- AND T1.SN = 'NAO'
	--GROUP BY T1.CHAVE



--SELECT T1.CHAVE, T1.cod_survey, T1.SN
--FROM GERA_TABELA_DO_TOTAIS_COM_SN AS T1
--RIGHT JOIN KPI.dbo.CELULAS_SN AS T2
--ON T2.CHAVE = T1.CHAVE
--WHERE T1.SN = 'NAO'

CREATE VIEW LISTA_SURVEYS_SN AS (
	SELECT T1.cod_survey
	FROM GERA_TABELA_DO_TOTAIS_COM_SN AS T1
	RIGHT JOIN KPI.dbo.CELULAS_SN AS T2
	ON T2.CHAVE = T1.CHAVE
	WHERE T1.SN = 'NAO' )


SELECT T1.*
FROM (SELECT T1.cod_survey
	FROM (
	SELECT NUM_FACHADA, COMPLEMENTO1,COMPLEMENTO2,COMPLEMENTO3,cod_survey,CONCAT(UF,ESTACAO_ABASTECEDORA,LEFT(CELULA,PATINDEX('%(%', CELULA) - 1)) AS CHAVE,
			IIF(fibra.dbo.Teste_Fachada(NUM_FACHADA) = 'NAO' AND fibra.dbo.Teste_Complemento_valido(
			IIF(COMPLEMENTO1 = '','',COMPLEMENTO1),
			IIF(COMPLEMENTO2 = '','',COMPLEMENTO2),
			IIF(COMPLEMENTO3 = '','',COMPLEMENTO3)
			) = 'NAO','NAO','SIM') AS SN
	FROM ENDERECOS_TOTAIS as TT -- ENDERECOS_TOTAIS É UMA VIEW, QUE FOI CRIADA LOGO ABAIXO
	WHERE CELULA <> 'NULL'	
	)/*GERA_TABELA_DO_TOTAIS_COM_SN*/ AS T1
	RIGHT JOIN KPI.dbo.CELULAS_SN AS T2
	ON T2.CHAVE = T1.CHAVE
	WHERE T1.SN = 'NAO') /*LISTA_SURVEYS_SN*/ AS SN
LEFT JOIN (
	SELECT *
	FROM OPENROWSET(  
	BULK 'C:\LOGICTEL\DOWNLOAD\Enderecos_Totais_20230530.csv',  
	FORMATFILE = 'C:\LOGICTEL\DOWNLOAD\BIEL\totais.xml',
	FIRSTROW = 2) AS TT
) AS T1
ON SN.cod_survey = T1.cod_survey


--DROP TABLE IF EXISTS KPI.dbo.CELULAS_SN

--DROP VIEW  IF EXISTS GERA_TABELA_DO_TOTAIS_COM_SN
--DROP VIEW  IF EXISTS ENDERECOS_TOTAIS

--SELECT NUM_FACHADA, COMPLEMENTO1,COMPLEMENTO2,COMPLEMENTO3 ,CONCAT(UF,ESTACAO_ABASTECEDORA,LEFT(CELULA,PATINDEX('%(%', CELULA) - 1)) AS CHAVE
--FROM ENDERECOS_TOTAIS


--CREATE VIEW GERA_TABELA_DO_TOTAIS_COM_SN AS (

--	SELECT NUM_FACHADA, COMPLEMENTO1,COMPLEMENTO2,COMPLEMENTO3,cod_survey,CONCAT(UF,ESTACAO_ABASTECEDORA,LEFT(CELULA,PATINDEX('%(%', CELULA) - 1)) AS CHAVE,
--			IIF(fibra.dbo.Teste_Fachada(NUM_FACHADA) = 'NAO' AND fibra.dbo.Teste_Complemento_valido(
--			IIF(COMPLEMENTO1 = '','',COMPLEMENTO1),
--			IIF(COMPLEMENTO2 = '','',COMPLEMENTO2),
--			IIF(COMPLEMENTO3 = '','',COMPLEMENTO3)
--			) = 'NAO','NAO','SIM') AS SN


--	FROM ENDERECOS_TOTAIS as TT -- ENDERECOS_TOTAIS É UMA VIEW, QUE FOI CRIADA LOGO ABAIXO
--	WHERE CELULA <> 'NULL' )


--CREATE VIEW ENDERECOS_TOTAIS AS
--	SELECT *
--	FROM OPENROWSET(  
--	BULK 'C:\LOGICTEL\DOWNLOAD\Enderecos_Totais_20230530.csv',  
--	FORMATFILE = 'C:\LOGICTEL\DOWNLOAD\BIEL\totais.xml',
--	FIRSTROW = 2) AS TT

DROP VIEW  IF EXISTS GERA_TABELA_DO_TOTAIS_COM_SN




