DROP TABLE IF EXISTS NETWIN_TOTAIS.dbo.ENDERECOS_TOTAIS
DROP TABLE IF EXISTS LISTAGEM.dbo.LISTAGEM_SURVEY


SELECT DISTINCT *
INTO NETWIN_TOTAIS.dbo.ENDERECOS_TOTAIS
FROM OPENROWSET(  
BULK 'C:\LOGICTEL\DOWNLOAD\Enderecos_Totais_20230626.csv',  
FORMATFILE = 'C:\LOGICTEL\DOWNLOAD\BIEL\totais.xml',
FIRSTROW = 2) AS TT


SELECT DISTINCT *
INTO LISTAGEM.dbo.LISTAGEM_SURVEY
FROM OPENROWSET(  
BULK 'C:\LOGICTEL\DOWNLOAD\LISTAGEM_DE_SURVEYS_2023-06-26_00h05m.csv',  
FORMATFILE = 'C:\LOGICTEL\10-XML\geral.xml',
FIRSTROW = 2)  AS LL


--SELECT TT.UF,TT.cod_survey AS SURVEY,TT.latitude AS LATITUDE_TOTAIS,TT.longitude AS LONGITUDE_TOTAIS, LL.N_EDIFICIO, LL.LATITUDE AS LATITUDE_LISTAGEM, LL.LONGITUDE AS LONGITUDE_LISTAGEM
--FROM NETWIN_TOTAIS.dbo.ENDERECOS_TOTAIS AS TT
--INNER JOIN LISTAGEM.dbo.LISTAGEM_SURVEY AS LL
--ON TT.cod_survey = LL.N_EDIFICIO



--CONTABILIZANDO OS SURVEYS COM COORDENADAS DIVERGENTES AGRUPANDO POR UF

SELECT UF ,COUNT(SURVEY) AS QTD_SURVEYS_DIVERGENTE
FROM (
	SELECT TT.uf AS UF,TT.estacao_abastecedora AS EST, TT.celula AS CELULA, TT.municipio AS MUNICIPIO,TT.bairro AS BAIRRO,TT.logradouro AS LOGRADOURO,TT.num_fachada AS NUM_FACHADA,TT.complemento1 AS COMPLEMENTO1,TT.complemento2 AS COMPLEMENTO2,TT.complemento3 AS COMPLEMENTO3 ,TT.cod_survey AS SURVEY,TT.latitude AS LATITUDE_TOTAIS,TT.longitude AS LONGITUDE_TOTAIS, LL.N_EDIFICIO, LL.LATITUDE AS LATITUDE_LISTAGEM, LL.LONGITUDE AS LONGITUDE_LISTAGEM
	FROM NETWIN_TOTAIS.dbo.ENDERECOS_TOTAIS AS TT
	INNER JOIN LISTAGEM.dbo.LISTAGEM_SURVEY AS LL
	ON TRIM(TT.cod_survey) = TRIM(LL.N_EDIFICIO)
	WHERE TT.uf IN ('RJ','SP','AC','AP','AM','PA','RO','RR','TO','AL','BA','CE','MA','PB','PE','PI','RN','SE')
	) AS CC
WHERE (TRIM(LATITUDE_TOTAIS) <> TRIM(LATITUDE_LISTAGEM)) OR (TRIM(LONGITUDE_TOTAIS) <> TRIM(LONGITUDE_LISTAGEM))
GROUP BY UF

SELECT TOP 10 *
FROM NETWIN_TOTAIS.dbo.ENDERECOS_TOTAIS

--CONTABILIZANDO OS SURVEYS AGRUPANDO POR UF
SELECT UF ,COUNT(SURVEY) AS QTD_SURVEYS
FROM (
	SELECT TT.uf AS UF,TT.estacao_abastecedora AS EST, TT.celula AS CELULA, TT.municipio AS MUNICIPIO,TT.bairro AS BAIRRO,TT.logradouro AS LOGRADOURO,TT.num_fachada AS NUM_FACHADA,TT.complemento1 AS COMPLEMENTO1,TT.complemento2 AS COMPLEMENTO2,TT.complemento3 AS COMPLEMENTO3 ,TT.cod_survey AS SURVEY,TT.latitude AS LATITUDE_TOTAIS,TT.longitude AS LONGITUDE_TOTAIS, LL.N_EDIFICIO, LL.LATITUDE AS LATITUDE_LISTAGEM, LL.LONGITUDE AS LONGITUDE_LISTAGEM
	FROM NETWIN_TOTAIS.dbo.ENDERECOS_TOTAIS AS TT
	INNER JOIN LISTAGEM.dbo.LISTAGEM_SURVEY AS LL
	ON TRIM(TT.cod_survey) = TRIM(LL.N_EDIFICIO)
	WHERE TT.uf IN ('RJ','SP','AC','AP','AM','PA','RO','RR','TO','AL','BA','CE','MA','PB','PE','PI','RN','SE')
	) AS CC
--WHERE (TRIM(LATITUDE_TOTAIS) <> TRIM(LATITUDE_LISTAGEM)) OR (TRIM(LONGITUDE_TOTAIS) <> TRIM(LONGITUDE_LISTAGEM))
GROUP BY UF

/*

	RETORNA O TOTAL DE SURVEYS E OS SURVEYS COM DIVERGENCIA DE COORDENADAS


*/

SELECT *
FROM (
	SELECT TT.uf AS UF,TT.estacao_abastecedora AS EST, TT.celula AS CELULA, TT.municipio AS MUNICIPIO,TT.bairro AS BAIRRO,TT.logradouro AS LOGRADOURO,TT.num_fachada AS NUM_FACHADA,TT.complemento1 AS COMPLEMENTO1,TT.complemento2 AS COMPLEMENTO2,TT.complemento3 AS COMPLEMENTO3 ,TT.cod_survey AS SURVEY,TT.latitude AS LATITUDE_TOTAIS,TT.longitude AS LONGITUDE_TOTAIS, LL.N_EDIFICIO, LL.LATITUDE AS LATITUDE_LISTAGEM, LL.LONGITUDE AS LONGITUDE_LISTAGEM
	FROM NETWIN_TOTAIS.dbo.ENDERECOS_TOTAIS AS TT
	INNER JOIN LISTAGEM.dbo.LISTAGEM_SURVEY AS LL
	ON TRIM(TT.cod_survey) = TRIM(LL.N_EDIFICIO)
	WHERE TT.uf IN ('RJ','SP','AC','AP','AM','PA','RO','RR','TO','AL','BA','CE','MA','PB','PE','PI','RN','SE')
	) AS CC
WHERE (TRIM(LATITUDE_TOTAIS) <> TRIM(LATITUDE_LISTAGEM)) OR (TRIM(LONGITUDE_TOTAIS) <> TRIM(LONGITUDE_LISTAGEM))




--CONTABILIZANDO OS SURVEYS AGRUPANDO POR UF
SELECT *
FROM (
	SELECT TT.uf AS UF,TT.estacao_abastecedora AS EST, TT.celula AS CELULA, TT.municipio AS MUNICIPIO,TT.bairro AS BAIRRO,TT.logradouro AS LOGRADOURO,TT.num_fachada AS NUM_FACHADA,TT.complemento1 AS COMPLEMENTO1,TT.complemento2 AS COMPLEMENTO2,TT.complemento3 AS COMPLEMENTO3 ,TT.cod_survey AS SURVEY,TT.latitude AS LATITUDE_TOTAIS,TT.longitude AS LONGITUDE_TOTAIS, LL.N_EDIFICIO, LL.LATITUDE AS LATITUDE_LISTAGEM, LL.LONGITUDE AS LONGITUDE_LISTAGEM
	FROM NETWIN_TOTAIS.dbo.ENDERECOS_TOTAIS AS TT
	INNER JOIN LISTAGEM.dbo.LISTAGEM_SURVEY AS LL
	ON TRIM(TT.cod_survey) = TRIM(LL.N_EDIFICIO)
	WHERE TT.uf IN ('RJ','SP','AC','AP','AM','PA','RO','RR','TO','AL','BA','CE','MA','PB','PE','PI','RN','SE')
	) AS CC
--WHERE (TRIM(LATITUDE_TOTAIS) <> TRIM(LATITUDE_LISTAGEM)) OR (TRIM(LONGITUDE_TOTAIS) <> TRIM(LONGITUDE_LISTAGEM))
