/*

	IMPORTANDO AS TABELAS


*/
/*
DROP TABLE IF EXISTS NETWIN_TOTAIS..ENDERECOS_TOTAIS
DROP TABLE IF EXISTS ASSOCIADOS..SERV_ASSOCIADOS

SELECT  *
INTO NETWIN_TOTAIS..ENDERECOS_TOTAIS
FROM OPENROWSET(  
	BULK 'C:\LOGICTEL\DOWNLOAD\Enderecos_Totais_20230703.csv',  
	FORMATFILE = 'C:\LOGICTEL\DOWNLOAD\BIEL\totais.xml',
	FIRSTROW = 2,
	CODEPAGE = 65001) AS TT


SELECT  *
INTO ASSOCIADOS..SERV_ASSOCIADOS
FROM OPENROWSET(  
	BULK 'C:\LOGICTEL\DOWNLOAD\SERVICOS_ASSOCIADOS_A_REDE_2023-07-02_09h25m.csv',  
	FORMATFILE = 'C:\LOGICTEL\DOWNLOAD\BIEL\associados.xml',
	FIRSTROW = 2,
	CODEPAGE = 65001) AS TT
*/	

/*

	IMPORTANDO A LSITA DA MARCIA

*/
/*
DROP TABLE IF EXISTS ASSOCIADOS..surveys_cdo

CREATE TABLE ASSOCIADOS..surveys_cdo(
CHAVE NVARCHAR(200),
REGIONAL NVARCHAR(200),
PSR NVARCHAR(200),
UF NVARCHAR(200),
ANG NVARCHAR(200), 
MUNICIPIO NVARCHAR(200),
TOTAL_HPs NVARCHAR(200),
NOME_CDO NVARCHAR(200),
LATITUDE NVARCHAR(200),
LONGITUDE NVARCHAR(200),
COD_SURVEY NVARCHAR(200),
LOGRADOURO NVARCHAR(200),
NUM_FACHADA NVARCHAR(200),
COMPLEMENTO NVARCHAR(200),
COMPLEMENTO2 NVARCHAR(200),
CEP NVARCHAR(200),
Bairro NVARCHAR(200)
)

BULK INSERT ASSOCIADOS..surveys_cdo
FROM 'C:\Users\vicente.carvalho\Desktop\surveys_cdo.csv'
WITH (
   FIRSTROW = 2,
   FIELDTERMINATOR = ';',
   ROWTERMINATOR = '\n',
   CODEPAGE = 65001
)
*/

SELECT TRIM(SS.COD_SURVEY), TT.
FROM ASSOCIADOS..surveys_cdo AS SS
LEFT JOIN NETWIN_TOTAIS..ENDERECOS_TOTAIS AS TT
ON TRIM(SS.COD_SURVEY) = TRIM(TT.cod_survey)




SELECT  SS.COD_SURVEY, AA.[Sigla Unidade Federativa] + '_' + AA.[Sigla Est Abastecedora] + '_' +  AA.[Célula CEOS] AS CHAVE_ASSOCIADOS, AA.[Código Survey]
FROM ASSOCIADOS..surveys_cdo AS SS
LEFT JOIN ASSOCIADOS..SERV_ASSOCIADOS AS AA
ON TRIM(SS.COD_SURVEY) = TRIM(AA.[Código Survey])
WHERE  AA.[Código Survey] IS NULL



/*
	ESTA CONSULTA ESTÁ RETORNANDO TODOS OS GPONS ASSOCIADOS AS CDO'S DA LISTA DA MARCIA
	USEI UF, ESTACAO E CDO PARA CRIAR UMA CHAVE DENTRO DO SERVICOS_ASSOCIADOS E COMPARAR COM A CHAVE DA LISTA DA MARCIA QUE UTILIZA A MESMA CHAVE.
*/

SELECT SS.CHAVE AS CHAVE_LISTA_MARCIA, AA.[Sigla Unidade Federativa] + '_' + AA.[Sigla Est Abastecedora] + '_' + AA.[CDOE I] AS CHAVE_ASSOCIADOS, SS.NOME_CDO AS CDO_LISTA_MARCIA, AA.[CDOE I] AS CDO_ASSOCIADOS,AA.[Sigla Unidade Federativa] AS UF, AA.[Sigla Est Abastecedora] AS ANG, AA.[Célula CEOS] AS CELL,[Código Survey] AS SURVEY_ASSOCIADOS, AA.[CFS ACESSOGPON] AS GPON
FROM ASSOCIADOS..surveys_cdo AS SS
LEFT JOIN ASSOCIADOS..SERV_ASSOCIADOS AS AA
ON SS.NOME_CDO = AA.[CDOE I] AND TRIM(SS.CHAVE) = TRIM(AA.[Sigla Unidade Federativa] + '_' + AA.[Sigla Est Abastecedora] + '_' + AA.[CDOE I])


/*

	AGRUPANDO POR CDO

*/

SELECT SS.CHAVE AS CHAVE_LISTA_MARCIA, COUNT(AA.[CFS ACESSOGPON]) AS QTD_GPON_ASSOCIADOS
FROM ASSOCIADOS..surveys_cdo AS SS
LEFT JOIN ASSOCIADOS..SERV_ASSOCIADOS AS AA
ON SS.NOME_CDO = AA.[CDOE I] AND TRIM(SS.CHAVE) = TRIM(AA.[Sigla Unidade Federativa] + '_' + AA.[Sigla Est Abastecedora] + '_' + AA.[CDOE I])
GROUP BY SS.CHAVE

/*

	QTD_GPON_ASSOCIADOS MAIOR QUE 16

*/
SELECT *
FROM(
	SELECT SS.CHAVE AS CHAVE_LISTA_MARCIA, COUNT(AA.[CFS ACESSOGPON]) AS QTD_GPON_ASSOCIADOS
	FROM ASSOCIADOS..surveys_cdo AS SS
	LEFT JOIN ASSOCIADOS..SERV_ASSOCIADOS AS AA
	ON SS.NOME_CDO = AA.[CDOE I] AND TRIM(SS.CHAVE) = TRIM(AA.[Sigla Unidade Federativa] + '_' + AA.[Sigla Est Abastecedora] + '_' + AA.[CDOE I])
	GROUP BY SS.CHAVE) AS T1
WHERE QTD_GPON_ASSOCIADOS > 16


/*

BUSCANDO OS SURVEYS ASSOCIADOS AOS GPON'S NO ENDERECOS_TOTAIS

*/


SELECT SS.CHAVE AS CHAVE_LISTA_MARCIA,SS.NOME_CDO , AA.[CFS ACESSOGPON] GPON, [Código Survey] AS SURVEY_ASSOCIADOS
FROM ASSOCIADOS..surveys_cdo AS SS
LEFT JOIN ASSOCIADOS..SERV_ASSOCIADOS AS AA
ON TRIM(SS.CHAVE) = TRIM(AA.[Sigla Unidade Federativa] + '_' + AA.[Sigla Est Abastecedora] + '_' + AA.[CDOE I])



SELECT SS.CHAVE AS CHAVE_LISTA_MARCIA, TT.estacao_abastecedora + '_' + TT.uf + '_' + TT.nome_cdo AS CHAVE_TOTAIS, TT.cod_survey, TT.cod_viabilidade, TT.tipo_survey, TT.qtd_ums, TT.ucs_residenciais, TT.ucs_comerciais
FROM ASSOCIADOS..surveys_cdo AS SS
LEFT JOIN NETWIN_TOTAIS..ENDERECOS_TOTAIS AS TT
ON TRIM(SS.CHAVE) = TRIM(TT.uf + '_' + TT.estacao_abastecedora + '_' + TT.nome_cdo)



